config/routes.rb
Rails.application.routes.draw do

    devise_for :admins
    
    get 'pages/home'

    get 'pages/about'
    
    devise_for :users

    resources :questions do
        resources :options do
            post 'upvote'
        end
    end

    root 'pages#home'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/answer.rb
class Answer < ActiveRecord::Base
    belongs_to :user
    belongs_to :question
    belongs_to :option, counter_cache: true
end

app/models/option.rb
class Option < ActiveRecord::Base
    belongs_to :question
    has_many :answers
end

app/models/question.rb
class Question < ActiveRecord::Base
    
    has_many :options, :dependent => :destroy
    has_many :answers, :dependent => :destroy
    has_many :users, through: :answers, :dependent => :destroy
    
    # make sure there is something in the field before submitting
    validates :question_text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
    
    has_many :answers
    has_many :questions, :through => :answers 
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
    
    def create
        @question = Question.find(params[:question_id])
        @option = @question.options.create(option_param)
        redirect_to question_path(@question)
    end
    
    def upvote
        @question = Question.find(params[:question_id])
        @option = Option.find(params[:option_id])
        Answer.create(user_id: current_user.id, question_id: @question.id, option_id: @option.id)
        redirect_to question_path(@question)
    end
    
    private
    
    def option_param
        params.require(:option).permit(:option_text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

    def profile
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    before_action :set_question, only: [:show, :edit, :update, :destroy]

    # GET /questions
    # GET /questions.json
    def index
        @questions = Question.includes(:options).all
    end

    # GET /questions/1
    # GET /questions/1.json
    def show
        @answers = Answer.all
        @users = User.all
    end

    # GET /questions/new
    def new
        @question = Question.new
    end

    # GET /questions/1/edit
    def edit
    end

    # POST /questions
    # POST /questions.json
    def create
        @question = Question.new(question_params)

        respond_to do |format|
            if @question.save
                format.html { redirect_to @question, notice: 'Question was successfully created.' }
                format.json { render :show, status: :created, location: @question }
            else
                format.html { render :new }
                format.json { render json: @question.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /questions/1
    # PATCH/PUT /questions/1.json
    def update
        respond_to do |format|
            if @question.update(question_params)
                format.html { redirect_to @question, notice: 'Question was successfully updated.' }
                format.json { render :show, status: :ok, location: @question }
            else
                format.html { render :edit }
                format.json { render json: @question.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /questions/1
    # DELETE /questions/1.json
    def destroy
        @question.destroy
        respond_to do |format|
            format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
        @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
        params.require(:question).permit(:question_text, :category, :fixture_date)
    end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def time_left()
        t = (question.fixture_date - DateTime.now).to_i
        
        t = math
        mm, ss = t.divmod(60)            #=> [4515, 21]
        hh, mm = mm.divmod(60)           #=> [75, 15]
        dd, hh = hh.divmod(24)           #=> [3, 3]
        "%d days, %d hours, %d minutes and %d seconds" % [dd, hh, mm, ss]
    end
    
    def get_season()
        
        time = Time.new
        
        if(time.month >= 3) && (time.month <= 5)
            "Yeah it's spring!"
        elsif(time.month > 5) && (time.month <= 8)
            "Everyone love summer"
        elsif(time.month > 8) && (time.month <= 10)
            "It's fall!"
        else
            "Yuck winter."
        end
    end
    
    def hello_greeting()
        time = Time.new
        
        if(time.hour >= 0) && (time.hour < 12)
            "Good morning, "
        elsif(time.hour >= 12) && (time.hour < 17)
            "Good afternoon, "
        elsif(time.hour >= 17) && (time.hour <= 24)
            "Good evening, "
        end
    end
    
    def random_fact()
        opening = [
            
            "The Wisdom of the Crowd is a theory which claims all the answers added together, divided by the total number of answers can be very close to the correct answer.",
            "The more people who vote on an answer, the stronger the collective opinion will be. Share it around to everyone you know!",
            "Strength in numbers! Invite your friends to get a more quantitative result!",
            
            "An alligator's tooth is said to increase luck in gambling!",
            "Do you have your lucky alligator tooth?",
            
            "What kind of bet are you looking at today? Football? Rugby? Horse-racing?",
            "Up to speed with the news on Olympics this year? Do you want Benchmark Your Bet for the upcoming games? Let us know!",
            "Thanks for using Benchmark Your Bet!"
            
            ]
        
        "#{opening[rand(8)]}"
    end
    
    def get_random_number(max_value = 10)
        rand(max_value)
    end
    
    def get_random_welcome()
        opening = ["What a great day.",
            "Welcome to our site.",
            "Thank you for stopping by."]
        
        middle = ["middle1.",
            "middle2",
            "middle3"]
        
        ending = ["end1",
            "end2",
            "end3"]
        
        "#{opening[rand(3)]} #{middle[rand(3)]} #{ending[rand(3)]}"
        
    end
    
    def count_to_10
        x = 2
        number_list = "1"
        
        loop do
            number_list = number_list + ", " + x.to_s
            x += 1
            break if x > 10
        end
        
        "#{number_list}"
    end
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Benchmark Your Bet</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width = device-width, initial-scale = 1.00, minimum-scale = 0.25, maximum-scale = 1.60">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css' rel='stylesheet' type='text/css' />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "application.js"%>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/simplemodal/1.4.4/jquery.simplemodal.min.js"%>
    <%= csrf_meta_tags %>
    <meta name="description" content="Benchmark Your Bet is a free web application aimed at people who enjoy betting, it helps them to make a more informed decision on what to vote for, rather than assuming the bookies’ odds.">
    <!-- Open Graph data -->
    <meta property="og:title" content="Benchmark Your Bet" />
    <meta property="og:type" content="product" />
    <meta property="og:url" content="http://benchmarkyourbet.com" />
    <meta property="og:image" content="http://arthurrigley.com/dev/horizontal-with-al-final.jpg" />
    <meta property="og:description" content="A free web application aimed at people who enjoy betting, it helps them to make a more informed decision on what to vote for, rather than assuming the bookies’ odds." />
</head>
<body>
    <div id="left">
        <%= link_to image_tag("logo.png", alt: "Benchmark Your Bet"), {:controller => '/pages', :action => 'home'}, {:class => 'websiteLogo'} %>
        
        <div class="headerWrap">
            <div id="user-greeting">
                <% if user_signed_in? %>
                    <p><%= hello_greeting() %> <%= current_user.email %>, <br> Not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>.</p>
                <% end %>
            </div>
            <div id="nav-trigger"><i class="fa fa-bars fa-3x"></i></div>
            <ul class="nav">
                <div id="nav-back"><i class="fa fa-times fa-3x"></i></div>
                <li><i class="fa fa-home fa-2x"></i> <%= link_to 'Home Page', {:controller => '/pages', :action => 'home'} %></li>
                <li><i class="fa fa-list-ul fa-2x"></i> <%= link_to 'Main Feed', {:controller => '/questions', :action => 'index'} %></li>
                <li><i class="fa fa-info-circle fa-2x"></i> <%= link_to 'About', {:controller => '/pages', :action => 'about'} %></li>
                <% if user_signed_in? %>
                    <li><i class="fa fa-user fa-2x"></i> <%= link_to 'Profile Settings', edit_user_registration_path %></li>
                    <li><i class="fa fa-sign-out fa-2x"></i> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                <li><i class="fa fa-sign-in fa-2x"></i> <%= link_to 'Log In', new_user_session_path, method: :get %></li>
                <li><i class="fa fa-user-plus fa-2x"></i> <%= link_to 'Free Sign Up', new_user_registration_path %></li>
                <% end %>
            </ul>
        </div>
        
    </div>
    <div id="content">
        <div id="alerts-wrapper">
            <div class="notice"><%= notice %></div>
            <div class="alert"><%= alert %></div>
        </div>
        <%= yield %>
    </div>
</body>
</html>

app/views/options/_form.html.erb
<%= form_for(@option) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing Option</h1>

<%= render 'form' %>

<%= link_to 'Show', @option %> |
<%= link_to 'Back', options_path %>

app/views/options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Options</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= link_to 'Show', option %></td>
        <td><%= link_to 'Edit', edit_option_path(option) %></td>
        <td><%= link_to 'Destroy', option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_option_path %>

app/views/options/new.html.erb
<h1>New Option</h1>

<%= render 'form' %>

<%= link_to 'Back', options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_option_path(@option) %> |
<%= link_to 'Back', options_path %>

app/views/pages/about.html.erb
<% provide(:title, "About") %>



<div class="header">
    <h1 class="title"><div class="bar"></div>ABOUT</h1>
    <h2 class="headerMessage"><%= random_fact() %></h2>
</div>
<div class="body">
    <div class="column one">
        <%= video_tag "/infographic-final.mp4", :controls => true, :autobuffer => true %>

    </div>
    <div class="column two">
        <h3>What is 'Benchmark Your Bet'?</h3>
        <p>Benchmark Your Bet is a free web application for betting enthusiasts. It aims to help you make a more informed decision on what to bet for.</p>
    </div>
    <div class="column two">
        <h3>How does it work?</h3>
        <p>By harnessing the power of crowdsource and using the wisdom of the crowd - you simply need to add your vote to the database, then you can use the rest of the userbase's opinion to greatly improve your decision, rather than assuming the odds!</p>
    </div>
    <div class="column two">
        <h3>I have questions!</h3>
        <p>I'd love to hear your thoughts, feedback or even requests! Please email me <a class="linkWhite" href="mailto:hi@arthurrigley.com">here</a>.</p>
        <p>If you have a request for a question, <a class="linkWhite" href="mailto:hi@arthurrigley.com?subject=Question Request">detail the fixture in an email</a> and I will confirm and push it to the application.</p>
    </div>
    <div class="column two">
        <h3>Devs</h3>
        <p>This is my first application using Ruby on Rails!</p>
    </div>
</div>

app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>

<div class="header">
    <h1 class="title"><div class="bar"></div>WELCOME</h1>
    <h2 class="headerMessage"><%= random_fact() %></h2>
</div>
<div class="body">
    <div class="column two textCenter">
        <h3>Howdy</h3>
        <p>Benchmark Your Bet is currently in an early beta stage!</p>
        <p>If you would like to request a fixture to be posted, <a class="linkWhite" href="mailto:hi@arthurrigley.com?subject=Question Request">detail it in an email to me</a> and I will confirm and push it to the application.</p>
        <h3><span class="textBold"><%= User.count %></span> subscribed users</h3>
        <h3><span class="textBold"><%= Question.count %></span> questions ready to vote for</h3>
        <h3><span class="textBold"><%= Answer.count %></span> answers from users</h3>
        <% if user_signed_in? %>
            <p>Use the navigation on your left or simply click <%= link_to 'here', {:controller => '/questions', :action => 'index'}, :class => 'linkWhite' %> to view the questions. Let's get voting!</p>
        <% else %>
            <p>Join the other users and start benchmarking your bet!</p>
            <p><%= link_to "Already have an account? Log in here!", new_user_session_path, :class => 'linkWhite' %></p>
            <p><%= link_to "Don't have an account? Sign up for free!", new_user_registration_path, :class => 'linkWhite' %></p>
        <% end %>
    </div>
    <div class="column two">
        <%= image_tag('al-single.png', :alt => 'Welcome to Benchmark Your Bet', :id => 'home-page-img') %>
    </div>
</div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_text %>
    <br>
    <%= f.text_area :question_text %>
    <br><br>
    <%= f.label :category %>
    <br>
    <%= f.text_field :category %>
    <br><br>
    <%= f.label :fixture_date %>
    <br>
    <%= f.datetime_select :fixture_date %>
    <br><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="header">
    <h1>EDIT QUESTION</h1>
</div>
<div class="body">
    <%= render 'form' %>

    <%= link_to 'Show', @question %> |
    <%= link_to 'Back', questions_path %>
</div>

app/views/questions/new.html.erb
<h1>NEW QUESTION</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<div class="header">
    <h1 class="qTitle"><div class="bar"></div><%= @question.question_text %></h1>
</div>
<div class="body">
    <div class="hasVoted">
        <% if Answer.exists?(:user_id => current_user.id, :question_id => @question.id) %>
        <p class="yesVote">You've voted!<br> <%= link_to 'Back To Questions', questions_path, :class => 'linkGreen' %></p>
        <% else %>
            <p class="noVote">You haven't voted yet, make your choice and confirm it to see the results <br> You only get one vote though!</p>
        <% end %>
    </div>
    <div id="options-wrapper">
    <% @question.options.in_groups_of(2, false).each do |group| %>
        <div class="row">
            <% group.each do |option| %>

                <div class="option">
                    <p class="optionText"><%= option.option_text %></p>
                    <% if current_user.admin? %>
                            <h3 class="optionCount"><%= option.answers.count %></h3>
                            <% if Answer.where(:user_id => current_user.id, :option_id => option.id).present? %>
                                <div class="votedFor"><i class="fa fa-check fa-1x"></i> Your Vote</div>
                            <% else %>
                                <%= link_to 'Vote', question_option_upvote_path(@question, option), data: { confirm: 'Are you sure you want to vote for this option?' }, :class => 'voteNow', method: :post %>
                            <% end %>
                    <% else %>
                        <% if Answer.exists?(:user_id => current_user.id, :question_id => @question.id) %>
                    <h3 class="optionCount"><%= pluralize(option.answers.count, "vote") %></h3>
                            <% if Answer.where(:user_id => current_user.id, :option_id => option.id).present? %>
                                <div class="votedFor"><i class="fa fa-check fa-1x"></i> Your Vote</div>
                            <% end %>
                        <% else %>
                            <%= link_to 'Vote', question_option_upvote_path(@question, option), data: { confirm: 'Are you sure you want to vote for this option?' }, :class => 'voteNow', method: :post %>
                        <% end %>
                    <% end %>
                </div>
            <% end %>
        </div>
    <% end %>
    </div>
    <div id="options-info-wrapper">
        <% if Answer.exists?(:user_id => current_user.id, :question_id => @question.id) %>
            <% @answers.where.not('message' => nil).where(:question_id => @question.id).each do |answer| %>
                <div class="messageWrap">
                    <p class="messageEmail"> 
                        <% user = User.find(answer.user_id) %>
                        <span class="textBold"><%= user.email %></span> commented:
                    </p>
                    <p class="messageContent"><%= answer.message %></p>
                </div>
            <% end %>
        <% else %>
            <p class="textWhite">Add an optional message to explain the reasoning behind your vote...</p>
                <%= text_area :message, autofocus: true %>
        <% end %>
    </div>
    <% if current_user.admin? %>
        <div id="admin-panel">
            <h2>Add Option</h2>
            <%= form_for([@question, @question.options.build]) do |f| %>
            <p>
                <%= f.label :option_text %><br />
                <%= f.text_field :option_text %>
            </p>
            <p>
                <%= f.submit %>
            </p>
            <% end %>
        </div>
    <% end %>
</div>